version: "3.9"

services:
  backend:
    build:
      context: ./pokemon-app-backend
    env_file:
      - ./pokemon-app-backend/.env
    expose:
      - "3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./pokemon-app-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
